name: core-build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  build:
    uses: azerothcore/reusable-workflows/.github/workflows/core_build_modules.yml@main
    with:
      module_repo: ${{ github.event.repository.name }}
